[package]
name = "bc-ur"
version = "0.1.1"
edition = "2021"
license-file = "LICENSE.md"
description = "Uniform Resources (UR) for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-ur-rust"
readme = "README.md"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/bc-ur"

[dependencies]
ur = "0.3.0"
dcbor = "0.7.0"

[dev-dependencies]
version-sync = "0.9"
