[package]
name = "bc-ur"
version = "0.1.7"
edition = "2021"
description = "Uniform Resources (UR) for Rust."
authors = ["Blockchain Commons"]
keywords = ["encoding", "cbor", "binary", "format", "serialization"]
repository = "https://github.com/BlockchainCommons/bc-ur-rust"
readme = "README.md"
license = "BSD-2-Clause-Patent"
categories = ["data-structures", "encoding"]
documentation = "https://docs.rs/bc-ur"

[dependencies]
dcbor = { path = "../bc-dcbor-rust" }
# dcbor = "0.8.1"

ur = "0.3.0"
thiserror = "1.0.48"
anyhow = "1.0"

[dev-dependencies]
version-sync = "0.9"
